<?php

declare(strict_types=1);

/**
 * Builds glyph strings from Future_Smooth.flf (TOIlet / FIGlet subset).
 * Run: php tools/generate_future_smooth.php
 */

$path = __DIR__ . '/Future_Smooth.flf';
$raw = file_get_contents($path);
if ($raw === false) {
    fwrite(STDERR, "Missing $path\n");
    exit(1);
}

$lines = preg_split('/\r\n|\r|\n/', $raw);
$header = $lines[0];
if (!preg_match('/^(?<sig>tlf2a.)\s+(?<h>\d+)\s+/u', $header, $m)) {
    fwrite(STDERR, "Bad header: $header\n");
    exit(1);
}

$hardBlank = mb_substr($m['sig'], 5, 1); // char after "tlf2a"
$height = (int) $m['h'];

$parts = preg_split('/\s+/u', trim($header));
$commentLines = (int) ($parts[5] ?? 0);

$idx = 1 + $commentLines;
if ($idx >= count($lines)) {
    fwrite(STDERR, "EOF before glyphs\n");
    exit(1);
}

/** @var array<int, array{string,string,string}> $byCode */
$byCode = [];

for ($code = 32; $code <= 126; $code++) {
    $glyphLines = [];
    for ($r = 0; $r < $height; $r++) {
        if ($idx >= count($lines)) {
            fwrite(STDERR, "Truncated at code $code\n");
            exit(1);
        }
        $glyphLines[] = $lines[$idx++];
    }
    $byCode[$code] = [
        cleanGlyphLine($glyphLines[0], $code, 0, $height, $hardBlank),
        cleanGlyphLine($glyphLines[1], $code, 1, $height, $hardBlank),
        cleanGlyphLine($glyphLines[2], $code, 2, $height, $hardBlank),
    ];
}

// Charset documented in AsciiText (same as TAAG URL)
$charset = 'abcdefghijklmnopqrstuvwxyz0123456789!:;,*$%&~"' . "'" . '{([-|`\\@)]}/+.';

$out = "<?php\n\ndeclare(strict_types=1);\n\n";
$out .= "// Generated by tools/generate_future_smooth.php from Future_Smooth.flf - do not edit by hand.\n\n";
$out .= "return [\n";

$keys = preg_split('//u', $charset, -1, PREG_SPLIT_NO_EMPTY);
foreach ($keys as $ch) {
    $code = ord($ch); // ASCII subset only
    if (!isset($byCode[$code])) {
        fwrite(STDERR, "Missing code for char " . bin2hex($ch) . "\n");
        exit(1);
    }
    $g = $byCode[$code];
    $maxW = max(mb_strlen($g[0]), mb_strlen($g[1]), mb_strlen($g[2]));
    $padded = [
        pad($g[0], $maxW),
        pad($g[1], $maxW),
        pad($g[2], $maxW),
    ];
    $out .= exportKey($ch) . ' => [' . exportLine($padded[0]) . ', ' . exportLine($padded[1]) . ', ' . exportLine($padded[2]) . "],\n";
}

$out .= "];\n";

$target = dirname(__DIR__) . '/src/Tivins/Tui/AsciiTextGlyphs.generated.php';
if (file_put_contents($target, $out) === false) {
    fwrite(STDERR, "Could not write $target\n");
    exit(1);
}
echo "Wrote $target\n";

function pad(string $line, int $w): string
{
    $len = mb_strlen($line);
    return $len >= $w ? $line : $line . str_repeat(' ', $w - $len);
}

function exportLine(string $s): string
{
    return var_export($s, true);
}

function exportKey(string $ch): string
{
    return match ($ch) {
        '\\' => "'\\\\'",
        "'" => "\"'\"",
        default => var_export($ch, true),
    };
}

function cleanGlyphLine(string $line, int $code, int $rowIndex, int $height, string $hardBlank): string
{
    $line = str_replace($hardBlank, ' ', $line);
    $ch = chr($code);

    // Lines marked only with @ (missing glyph placeholders): keep visible part before @
    if (str_ends_with($line, '@')) {
        $line = preg_replace('/@+$/u', '', $line) ?? $line;
        return rtrim($line, ' ');
    }

    $stripCount = ($rowIndex === $height - 1) ? $height : 1;
    $cu = strtolower($ch);

    for ($n = 0; $n < $stripCount; $n++) {
        if ($line === '') {
            break;
        }
        $last = mb_substr($line, -1);
        if ($last === '@') {
            $line = mb_substr($line, 0, -1);
            continue;
        }
        if ($ch !== ' ' && (strtolower($last) === $cu || ($cu === ' ' && $last === ' '))) {
            // Width markers duplicate the glyph letter; avoid stripping interior spaces for space glyph
            if ($cu === ' ' && $last === ' ') {
                $line = mb_substr($line, 0, -1);
                continue;
            }
            if ($cu !== ' ') {
                $line = mb_substr($line, 0, -1);
                continue;
            }
        }
        break;
    }

    return rtrim($line, ' ');
}
